FROM mcr.microsoft.com/devcontainers/base:alpine

RUN sudo apk add nodejs npm \
    && sudo apk add openjdk17 openjdk17-jre \
    && sudo apk add python3 py3-pip py3-flake8 py3-autopep8 py3-yapf py3-mypy py3-pycodestyle py3-virtualenv py3-pytest py3-pylint
